/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>

#define RCC_BASE    0x40023800
#define GPIOC_BASE  0x40020800

#define RCC_AHB1ENR   (*(volatile uint32_t *)(RCC_BASE + 0x30))
#define GPIOC_MODER   (*(volatile uint32_t *)(GPIOC_BASE + 0x00))
#define GPIOC_ODR     (*(volatile uint32_t *)(GPIOC_BASE + 0x14))

void delay(uint32_t count)
{
    while (count--)
    {
        __asm volatile("nop"); // Prevent compiler optimizations
    }
}

int main(void)
{
    // 1. Enable GPIOC clock (Bit 2 of RCC_AHB1ENR)
    RCC_AHB1ENR |= (1 << 2);

    // 2. Set PC13 as General Purpose Output Mode (MODER13[1:0] = 01)
    GPIOC_MODER &= ~(3 << (13 * 2)); // Clear mode bits
    GPIOC_MODER |= (1 << (13 * 2));  // Set mode to Output

    while (1)
    {
        // 3. Toggle PC13 (LED ON/OFF)
        GPIOC_ODR ^= (1 << 13);

        // 4. Delay
        delay(1000000); // Adjust based on your system clock
    }
}
